[feeluown-core]
src.pypi = "feeluown"
fetch.pypi = "feeluown"

[qliveplayer]
src.github = "THMonster/QLivePlayer"
fetch.github = "THMonster/QLivePlayer"
# fetchgit options
git.fetchSubmodules = true

[apple-emoji]
# A fake version, which is unused in the fetcher
src.manual = "0.0.0.20200413"
fetch.url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/latest/AppleColorEmoji.ttf"

[nvfetcher-git]
# Follow the latest git commit
src.git = "https://github.com/berberman/nvfetcher"
fetch.github = "berberman/nvfetcher"

[gcc-10]
# Find a tag by regex
src.github_tag = "gcc-mirror/gcc"
# nvchecker list options, which uses regex to filter out a list of tags
src.include_regex = "releases/gcc-10.*"
fetch.github = "gcc-mirror/gcc"

[vim]
src.webpage = "http://ftp.vim.org/pub/vim/patches/7.3/"
src.regex = "7\\.3\\.\\d+"
fetch.github = "vim/vim"
# nvchecker global options, which adds prefix `v` to the version number  
src.from_pattern = "(.+)"
src.to_pattern = "v\\1"

[fd]
src.github = "sharkdp/fd"
fetch.github = "sharkdp/fd"
# Pull the contents of `Cargo.lock` into generated nix expr
extract = ["Cargo.lock"]

[rust-git-dependency-example]
src.manual = "8a5f37a8f80a3b05290707febf57e88661cee442"
fetch.git = "https://gist.github.com/NickCao/6c4dbc4e15db5da107de6cdb89578375"
# Calculate outputHashes for git dependencies in cargo lock
cargo_lock = "Cargo.lock"

[vscode-LiveServer]
src.openvsx = "ritwickdey.LiveServer"
fetch.openvsx = "ritwickdey.LiveServer"
passthru = { publisher = "ritwickdey", name = "LiveServer" }

[cmd-example]
src.cmd = "echo v2.5"
fetch.github = "lilydjwg/nvchecker"
